* DESCRIPTION

  This project aims to be integrated with [[http://www.quattor.org][Quattor]]. It allows to
  associate arbitrary code with any annotation in the header of the
  Pan templates.

  The main usage is to generate a Pan template out of an external
  source, f.i, contents of an LDAP server.

* TODO [#A] Document the code properly[1/2]

** DONE Some modules and functions lack documentation strings.

   Maybe some day somebody will wish to debug or extend the
   project. :)

   In any case, now only operations that *require* access to CDB lack
   automated testing, as it doesn't make sense out of CERN.

** TODO The tests could have even clearer examples about the usage.

   Maybe I'll want to remember how I did things some months ago.

* TODO [#B] Be more modular[0/3]

** TODO Write a module to walk through the checkout

   It is done in the main module now, and it's ugly and long.

** TODO Write separated modules for interacting with different CDB implementations?

   CDB interactions are going to be way too special to share the code
   with SCDB. :(

** TODO Put in a subdirectory any actions.

   To ease plugging of actions.

* DONE [#C] Support user-plugged actions and user-specified actions[1/1]

** DONE Add a configuration file with the headers, associated modules, and "top-level" callables.
   
